version: "3.7"

volumes:
  mysql-data: {}

services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
    volumes:
      - ./app:/var/www/html/app
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8090:80"

  php-fpm:
    build:
      context: ./
      dockerfile: docker/php-fpm/Dockerfile
    environment:
      PHP_IDE_CONFIG: serverName=Test
    volumes:
      - ./app:/var/www/html/app

  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=sergey
      - MYSQL_PASSWORD=12345
      - MYSQL_DATABASE=laravel_shop

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "8095:8080"
